language: go

notifications:
  email: false

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - sudo apt-get -qq update
  - sudo apt-get install -y libosmgpsmap-dev libsoup-dev
  - sudo ln -s /usr/lib/pkgconfig/osmgpsmap.pc /usr/lib/pkgconfig/osmgpsmap-1.0.pc
  - dpkg -l
  - dpkg-query -L libsoup
  - dpkg-query -L libsoup-dev

install:
  - go get ./...

before_script:
  - wget https://gist.github.com/mewmew/379014c9a2e6885e238d/raw/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
